FROM oven/bun:1
WORKDIR /usr/src/app

COPY package.json bun.lockb ./

RUN bun install --frozen-lockfile
COPY next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./
COPY src ./src
RUN bun run build

ENV NODE_ENV=production
USER bun

EXPOSE 3000/tcp
ENTRYPOINT ["bun", "run", "start"]
