FROM oven/bun:1
WORKDIR /usr/src/app

COPY package.json bun.lockb ./

RUN bun install --frozen-lockfile
COPY next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./
COPY public ./public
COPY src ./src

ENV NODE_ENV=production
ARG NEXT_PUBLIC_WS_PUBLIC_URL
ENV NEXT_PUBLIC_WS_PUBLIC_URL=${NEXT_PUBLIC_WS_PUBLIC_URL}
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN bun run build

USER bun
EXPOSE 3000/tcp
ENTRYPOINT ["bun", "run", "start"]
